# Generated by Django 5.0 on 2024-01-18 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseManagement', '0005_orderassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarehouseManagement.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarehouseManagement.product')),
            ],
        ),
    ]
