# Generated by Django 5.0 on 2024-01-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseManagement', '0009_remove_assignedorder_delivered_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedorder',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='assignedorder',
            name='location',
        ),
        migrations.AddField(
            model_name='assignedorder',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignedorder',
            name='dispatched_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignedorder',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignedorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='assignedorder',
            name='transit_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
