# Generated by Django 5.0 on 2024-01-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseManagement', '0010_remove_assignedorder_is_delivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedorder',
            name='estimated_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
