# Generated by Django 5.0 on 2024-01-19 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseManagement', '0011_alter_assignedorder_estimated_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_orders', to='WarehouseManagement.order'),
        ),
    ]
